### ISSUE TITLE
**Költőválasztás**

### ISSUE THREAD

**Issue by anda-kristof** [anda-kristof/Tavaszi-versek-A#1]
Válasszatok egy költőt és tőle 3 verset és töltse fel egy külön txt fájlba . Kommentbe írjátok oda a választottakat.

**Comment by borbely-dominik-peter** [comment]
3 vers kell költőnként
Petőfi
-A tavaszhoz
-Minek nevezzelek?
-Jőj, Tavasz, Jőj

**Comment by anda-kristof** [comment]
Csukás István
-A sínen ül egy fehér nyúl
-Tavaszi vers
-Isten megnyomja a tavasz-gombot

**Comment by bicskey-balazs** [comment]
József Attila
-TAVASZ VAN! GYÖNYÖRŰ!
-TAVASZI ÉNEK
-TAVASZI SÁR
